version: "3"

vars:
  PKGNAME:
    sh: "sed -n 's/Package: *\\([^ ]*\\)/\\1/p' DESCRIPTION"
  PKGVERS:
    sh: "sed -n 's/Version: *\\([^ ]*\\)/\\1/p' DESCRIPTION"
  PKGSRC:
    sh: "basename $(pwd)"

tasks:
  default:
    deps: [install]

  clean:
    cmds:
      - rm -rf src/*.o src/*.so

  docs:
    cmds:
      - 'Rscript -e ''devtools::document(roclets = c("rd", "collate",
        "namespace"))'''

  build:
    deps: [docs]
    cmds:
      - cd .. && R CMD build {{.PKGSRC}} --no-manual --no-build-vignettes

  build-cran:
    cmds:
      - cd .. && R CMD build {{.PKGSRC}}

  install:
    cmds:
      - R CMD INSTALL . --no-multiarch --with-keep.source

  clean-install:
    cmds:
      - R CMD INSTALL --preclean --no-multiarch --with-keep.source {{.PKGNAME}}

  check:
    cmds:
      - Rscript -e 'devtools::check()'

  test:
    cmds:
      - Rscript -e 'devtools::test()'

  format:
    cmds:
      - air format .
      - panache format .

  lint:
    cmds:
      - air format --check .
      - panache lint .

  verify:
    cmds:
      - task: check
      - air format --check .
      - panache format --check .
      - panache lint .

  readme:
    cmds:
      - Rscript -e 'devtools::build_readme()'

  vignettes:
    cmds:
      - Rscript -e 'devtools::build_vignettes()'
