name = "{{cookiecutter.project_name}}"
uuid = "00000000-0000-0000-0000-000000000000"
authors = ["{{cookiecutter.author}} <{{cookiecutter.email}}> and contributors"]
version = "0.0.1"

[compat]
julia = "1.6"
Test = "1.6"
Aqua = "0.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
