version: "3"

vars:
  JULIA: julia

tasks:
  default:
    desc: Install dependencies
    cmds:
      - task: install

  install:
    desc: Install and instantiate package dependencies
    cmds:
      - '{{.JULIA}} -e "using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()"'

  test:
    desc: Run package tests
    cmds:
      - '{{.JULIA}} --project=. -e "using Pkg; Pkg.test()"'

  docs:
    desc: Build documentation
    cmds:
      - '{{.JULIA}} --project=docs/ -e "using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()"'
      - "{{.JULIA}} --project=docs/ docs/make.jl"

  readme:
    desc: Generate README from Quarto document
    cmds:
      - '{{.JULIA}} --project=readme/ -e "using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()"'
      - quarto render readme/README.qmd --output README.md
      - mv readme/README_files README_files
